#!/bin/bash

faudio_install() {

# kill wineserver before installation to make sure correct wine version is used
wineserver -k

if [ $WINEARCH == "win64" ]; then
  echo "Linking dlls to system32..."
  WINEPREFIX="$WINEPREFIX" setup_faudio64
  ln -sf /usr/x86_64-w64-mingw32/bin/libwinpthread-1.dll $WINEPREFIX/drive_c/windows/system32/libwinpthread-1.dll
  
  echo "Linking dlls to syswow64..."
  WINEPREFIX="$WINEPREFIX" setup_faudio3264
  ln -sf /usr/i686-w64-mingw32/bin/libwinpthread-1.dll $WINEPREFIX/drive_c/windows/syswow64/libwinpthread-1.dll
fi

if [ $WINEARCH == "win32" ]; then
  echo "Linking dlls to system32..."
  WINEPREFIX="$WINEPREFIX" setup_faudio32
  ln -sf /usr/i686-w64-mingw32/bin/libwinpthread-1.dll $WINEPREFIX/drive_c/windows/system32/libwinpthread-1.dll
fi

}

if [ -n $1 ]; then
    if [ -d $1 ]; then
    WINEPREFIX="$1"
        if [ "$2" == "32" ]; then
          echo "x86 prefix"
          WINEARCH="win32"
        elif [ "$2" == "64" ]; then
          echo "x64 prefix"
          WINEARCH="win64"
        elif [ -d "$1/drive_c/Program Files (x86)" ]; then
          echo "assuming x64 prefix"
          WINEARCH="win64"
        else
          echo "assuming x86 prefix"
          WINEARCH="win32"
        fi
    fi
faudio_install
fi
