#!/bin/bash

if [ "$_use_staging" == "true" ]; then
  cd "${srcdir}"/"${_stgsrcdir}"
  if git merge-base --is-ancestor 67035d62f74ae1cdfc5658ce55bbbc3a15c5988b HEAD; then
  cd "${srcdir}"/"${_winesrcdir}"

  hotfixer() {
	local _patches=("$_where"/wine-tkg-patches/hotfixes/*."${_userpatch_ext}revert")
	if [ ${#_patches[@]} -ge 2 ] || [ -e "${_patches}" ]; then
	  if [ "$_user_patches_no_confirm" != "true" ]; then
	    msg2 "Found ${#_patches[@]} reverting hotfix:"
	    printf '%s\n' "${_patches[@]}"
	    read -rp "Do you want to install it/them?"$'\n> N/y : ' _CONDITION;
	  fi
	  if [ "$_CONDITION" == "y" ] || [ "$_user_patches_no_confirm" == "true" ]; then
	    for _f in "${_patches[@]}"; do
	      if [ -e "${_f}" ]; then
	        msg2 "######################################################"
	        msg2 ""
	        msg2 "Applying reverting hotfix ${_f}"
	        msg2 ""
	        msg2 "######################################################"
	        patch -Np1 -R < "${_f}"
	        echo "Applied reverting hotfix ${_f}" >> "$_where"/last_build_config.log
	      fi
	    done
	  fi
	fi

	_patches=("$_where"/wine-tkg-patches/hotfixes/*."${_userpatch_ext}patch")
	if [ ${#_patches[@]} -ge 2 ] || [ -e "${_patches}" ]; then
	  if [ "$_user_patches_no_confirm" != "true" ]; then
	    msg2 "Found ${#_patches[@]} hotfix:"
	    printf '%s\n' "${_patches[@]}"
	    read -rp "Do you want to install it/them?"$'\n> N/y : ' _CONDITION;
	  fi
	  if [ "$_CONDITION" == "y" ] || [ "$_user_patches_no_confirm" == "true" ]; then
	    for _f in "${_patches[@]}"; do
	      if [ -e "${_f}" ]; then
	        msg2 "######################################################"
	        msg2 ""
	        msg2 "Applying hotfix ${_f}"
	        msg2 ""
	        msg2 "######################################################"
	        patch -Np1 < "${_f}"
	        echo "Applied hotfix ${_f}" >> "$_where"/last_build_config.log
	      fi
	    done
	  fi
	fi
  }
  else
    hotfixer() {
    msg2 "No hotfix for you"
    }
  fi
else
  hotfixer() {
  msg2 "No hotfix for you"
  }
fi
