#!/bin/bash

# TkGlitch's D9VK Updater - ti3nou@gmail.com

# BUILD HEAD OF THE CHOSEN BRANCH WITH : ./upd9vk build - (Edit D9VK_BRANCH to point to the branch you want)

# UPDATE WITH : ./upd9vk /path/to/wine/prefix - (WINEARCH will be autodetected)

# BATCH UPDATE WITH : ./upd9vk batch - (Edit PREFIXES_ROOT variable to point to your prefixes dir)

# LUTRIS UPDATE WITH : ./upd9vk lutris - (Put 'TkG' as D9VK version in lutris afterwards to use your fresh build)

# PROTON-TKG READY WITH : ./upd9vk proton-tkg

# FOR BOTH UPDATE AND BATCH UPDATE : optional - build number of the build you want to install
# ex for UPDATE: ./upd9vk /home/user/WinePrefixes/DEBUG f4a92a685f8b2f135dc6fe493ea9ce726aa79a52-2018-05-05-16:14:00
# ex for BATCH UPDATE: ./upd9vk batch f4a92a685f8b2f135dc6fe493ea9ce726aa79a52-2018-05-05-16:14:00

# Putting patch files in D9VKBUILD/patches will auto-apply them if the extension is .d9vkpatch, auto-revert them if the extension is .d9vkrevert, or ignore them if any other extension (or none) is used

D9VK_BRANCH=master # D9VK branch to use
CUSTOM_COMMIT=0 # Set to 1 to enable custom commit checkout
D9VK_COMMIT= # targetted custom commit
D9VK_AUTOUPDATE=1 # Git pull (Sync) with clean source before building

PATCHIN=1 # Enables auto-application of all patches present in ./D9VKBUILD/patches - It WILL make your tree dirty if any patch is applied
DIRTYIN=1 # 0: Clear source dir only if marked as dirty from patching - 1: Always clear source dir and redownload from git - 2: Always ignore source dir removal even if dirty

PREFIXES_ROOT=$HOME/wineprefixes # Path to the root folder containing your wine prefixes for batch installing/updating

ROOT=$PWD

build() {
mkdir -p D9VKBUILD
mkdir -p D9VKBUILD/patches

if [ "$DIRTYIN" != "2" ]; then
  if [ -e "d9vk-$D9VK_BRANCH.d9vkdirty" ] || [ "$DIRTYIN" == "1" ]; then
  rm -R -f d9vk-$D9VK_BRANCH
  echo "#################"
  echo ""
  echo "YOUR TREE WAS CONSIDERED DIRTY AND HAS BEEN CLEARED"
  echo ""
  echo "#################"
  rm $D9VK_BRANCH.d9vkdirty
  fi
else
  echo "#################"
  echo ""
  echo "YOU DIRTY BOI.."
  echo ""
  echo "#################"
fi

mkdir d9vk-$D9VK_BRANCH

cd d9vk-$D9VK_BRANCH

if [ ! -e package-release.sh ]; then
  git init .
  git remote add -t \* -f origin https://github.com/Joshua-Ashton/d9vk.git
  git checkout $D9VK_BRANCH
fi

if [ "$D9VK_AUTOUPDATE" == "1" ]; then
  git pull
fi

if [ -n $D9VK_COMMIT ] && [ "$CUSTOM_COMMIT" == "1" ]; then
  git checkout $D9VK_COMMIT
fi

GIT_HEAD=$(git rev-parse HEAD)-`date '+%Y-%m-%d-%H:%M:%S'`

if [ "$PATCHIN" == "1" ]; then
  for F in ../D9VKBUILD/patches/*.d9vkrevert; do
    if [ -e "${F}" ]; then
      echo "#################"
      echo ""
      echo "REVERTING PATCH ${F}"
      echo ""
      echo "#################"
      patch -Np1 -R < ${F} && echo "This means that branch $D9VK_BRANCH was altered by patching and will be cleared next time you build" >> ../$D9VK_BRANCH.d9vkdirty
    else
      echo "#################"
      echo ""
      echo "NO REVERT PATCH DETECTED - MOVING ON"
      echo ""
      echo "#################"
    fi
  done
  for F in ../D9VKBUILD/patches/*.d9vkpatch; do
    if [ -e "${F}" ]; then
      echo "#################"
      echo ""
      echo "APPLYING PATCH ${F}"
      echo ""
      echo "#################"
      patch -Np1 < ${F} && echo "This means that branch $D9VK_BRANCH was altered by patching and will be cleared next time you build" >> ../$D9VK_BRANCH.d9vkdirty
    else
      echo "#################"
      echo ""
      echo "NO PATCH DETECTED - MOVING ON"
      echo ""
      echo "#################"
    fi
  done
fi

echo "#################"
echo ""
echo "BUILDING"
echo ""
echo "#################"
./package-release.sh $D9VK_BRANCH ../D9VKBUILD --no-package

# Workarounds dxvk dirs
if [ -d ../D9VKBUILD/dxvk-$D9VK_BRANCH ]; then
  mv ../D9VKBUILD/dxvk-$D9VK_BRANCH ../D9VKBUILD/d9vk-$D9VK_BRANCH
fi

if [ -d ../D9VKBUILD/d9vk-$D9VK_BRANCH/x32 ] && [ -d ../D9VKBUILD/d9vk-$D9VK_BRANCH/x64 ]; then
  mv -v -T ../D9VKBUILD/d9vk-$D9VK_BRANCH/x32 ../D9VKBUILD/d9vk-$D9VK_BRANCH/win32
  mv -v -T ../D9VKBUILD/d9vk-$D9VK_BRANCH/x64 ../D9VKBUILD/d9vk-$D9VK_BRANCH/win64
  mkdir -p ../D9VKBUILD/$D9VK_BRANCH/$GIT_HEAD
  mv -v -T ../D9VKBUILD/d9vk-$D9VK_BRANCH/win32 ../D9VKBUILD/$D9VK_BRANCH/$GIT_HEAD/win32
  cp ../D9VKBUILD/setup_d9vk32.sh ../D9VKBUILD/$D9VK_BRANCH/$GIT_HEAD/win32/setup_d9vk.sh
  mv -v -T ../D9VKBUILD/d9vk-$D9VK_BRANCH/win64 ../D9VKBUILD/$D9VK_BRANCH/$GIT_HEAD/win64
  cp ../D9VKBUILD/setup_d9vk64.sh ../D9VKBUILD/$D9VK_BRANCH/$GIT_HEAD/win64/setup_d9vk.sh
  rm -R -f ../D9VKBUILD/d9vk-$D9VK_BRANCH
  echo "Your files were built in $ROOT/D9VKBUILD/$D9VK_BRANCH/$GIT_HEAD"
  rm -f ../D9VKBUILD/$D9VK_BRANCH/last-HEAD
  echo "CURRENT_HEAD=$GIT_HEAD" >> ../D9VKBUILD/$D9VK_BRANCH/last-HEAD
else
  rm -rf ../D9VKBUILD/*-$D9VK_BRANCH
fi

}

update() {

if [ -d $ROOT/D9VKBUILD ]; then

  . $ROOT/D9VKBUILD/$D9VK_BRANCH/last-HEAD

  # kill wineserver before installation to make sure correct wine version is used
  wineserver -k

  WINECMD=${WINE-wine}

  if [ $WINECMD = "wine" ]; then
    if [ $WINEARCH = "win64" ]; then
        WINECMD="wine64"
    else
        WINECMD="wine"
    fi
  fi

  if [ -z $2 ]; then
    cd $ROOT/D9VKBUILD/$D9VK_BRANCH/$CURRENT_HEAD
  elif [ -d $ROOT/D9VKBUILD/$2 ];then
    cd $ROOT/D9VKBUILD/$2
  else
    echo "#################################"
    echo ""
    echo "  D9VKBUILD/$2 directory not found !!"
    echo ""
    echo "#################################"
  fi

  if [ -d "win32" ] && [ -d "win64" ]; then
    WINEARCH=$WINEARCH WINEPREFIX="$WINEPREFIX" bash $WINEARCH/setup_d9vk.sh

    if [ $WINEARCH = "win64" ]; then
        WINEARCH=$WINEARCH WINEPREFIX="$WINEPREFIX" bash win32/setup_d9vk.sh
    fi

    echo "#########################################"
    echo ""
    echo "  D9VK updated in $WINEPREFIX - $WINEARCH"
    echo ""
    echo "#########################################"
  fi

  wineserver -k

else
  echo "################################################################"
  echo ""
  echo "You need to build before you can update ! Run upd9vk build first"
  echo ""
  echo "################################################################"
fi
}

# External / Dynamic
if [ -n $1 ] && [ "$1" != "batch" ] && [ "$1" != "build" ] && [ "$1" != "lutris" ] && [ "$1" != "proton-tkg" ]; then
  if [ -d $1 ]; then
    WINEPREFIX="$1"
    if [ "$2" == "32" ]; then
      echo "x86 prefix"
      WINEARCH="win32"
    elif [ "$2" == "64" ]; then
      echo "x64 prefix"
      WINEARCH="win64"
    elif [ -d "$1/drive_c/Program Files (x86)" ]; then
      echo "assuming x64 prefix"
      WINEARCH="win64"
    else
      echo "assuming x86 prefix"
      WINEARCH="win32"
    fi
  fi
  update
fi

# Batch
if [ "$1" == "batch" ] && [ ! -z $PREFIXES_ROOT ]; then
  for D in $PREFIXES_ROOT/*; do
    if [ -d "${D}" ]; then
      echo "${D}"
      if [ -d "${D}/drive_c" ]; then
        WINEPREFIX="${D}"
        if [ -d "${D}/drive_c/Program Files (x86)" ]; then
          WINEARCH="win64"
        else
          WINEARCH="win32"
        fi
        update
      fi
    fi
  done
fi

# Lutris
if [ "$1" == "lutris" ]; then

  wineserver -k

    if [ ! -f ./D9VKBUILD/$D9VK_BRANCH/last-HEAD ]; then

      echo "You need to build before you can update ! Run upd9vk build first"

    else

      . ./D9VKBUILD/$D9VK_BRANCH/last-HEAD

      rm -rv $HOME/.local/share/lutris/runtime/dxvk/TkG/x64/d3d9.dll
      rm -rv $HOME/.local/share/lutris/runtime/dxvk/TkG/x32/d3d9.dll
      #mkdir -p $HOME/.local/share/lutris/runtime/d9vk/TkG/x64
      #mkdir -p $HOME/.local/share/lutris/runtime/d9vk/TkG/x32
      cp -rv ./D9VKBUILD/$D9VK_BRANCH/$CURRENT_HEAD/win64/* $HOME/.local/share/lutris/runtime/dxvk/TkG/x64
      cp -rv ./D9VKBUILD/$D9VK_BRANCH/$CURRENT_HEAD/win32/* $HOME/.local/share/lutris/runtime/dxvk/TkG/x32

      echo ""
      echo "###########################################################"
      echo ""
      echo "Put 'TkG' as D9VK version in lutris to use your fresh build"
      echo ""
      echo "###########################################################"

    fi

fi

# Proton-tkg
if [ "$1" == "proton-tkg" ]; then

  wineserver -k

    if [ ! -f ./D9VKBUILD/$D9VK_BRANCH/last-HEAD ]; then

      echo "You need to build before you can update ! Run upd9vk build first"

    else

      . ./D9VKBUILD/$D9VK_BRANCH/last-HEAD

      rm -rf ../proton-tkg/d9vk
      mkdir -p ../proton-tkg/d9vk/x64
      mkdir -p ../proton-tkg/d9vk/x32
      cp -rv ./D9VKBUILD/$D9VK_BRANCH/$CURRENT_HEAD/win64/* ../proton-tkg/d9vk/x64
      cp -rv ./D9VKBUILD/$D9VK_BRANCH/$CURRENT_HEAD/win32/* ../proton-tkg/d9vk/x32

      echo ""
      echo "###############################################################"
      echo ""
      echo "This D9VK build will be integrated to your next Proton-tkg build"
      echo ""
      echo "###############################################################"

    fi

fi

# Build from latest master branch
if [ "$1" == "build" ]; then

  time build

fi

exit
