#!/bin/bash

# TkGlitch's DXVK Updater - ti3nou@gmail.com

# BUILD HEAD OF THE CHOSEN BRANCH WITH : ./updxvk build - (Edit DXVK_BRANCH to point to the branch you want)

# UPDATE WITH : ./updxvk /path/to/wine/prefix - (WINEARCH will be autodetected) - Adding "vulkansdk" after your path will also install vulkansdk to this prefix

# BATCH UPDATE WITH : ./updxvk batch - (Edit PREFIXES_ROOT variable to point to your prefixes dir)

# LUTRIS UPDATE WITH : ./updxvk lutris - (Put 'TkG' as DXVK version in lutris afterwards to use your fresh build)

# PROTON-TKG READY WITH : ./updxvk proton-tkg

# FOR BOTH UPDATE AND BATCH UPDATE : optional - build number of the build you want to install
# ex for UPDATE: ./updxvk /home/user/WinePrefixes/DEBUG f4a92a685f8b2f135dc6fe493ea9ce726aa79a52-2018-05-05-16:14:00
# ex for BATCH UPDATE: ./updxvk batch f4a92a685f8b2f135dc6fe493ea9ce726aa79a52-2018-05-05-16:14:00

# Putting patch files in DXVKBUILD/patches will auto-apply them if the extension is .dxvkpatch, auto-revert them if the extension is .dxvkrevert, or ignore them if any other extension (or none) is used

cat << 'EOM'
       .---.`               `.---.
    `/syhhhyso-           -osyhhhys/`
   .syNMdhNNhss/``.---.``/sshNNhdMNys.
   +sdMh.`+MNsssssssssssssssNM+`.hMds+
   :syNNdhNNhssssssssssssssshNNhdNNys:
    /ssyhhhysssssssssssssssssyhhhyss/
    .ossssssssssssssssssssssssssssso.
   :sssssssssssssssssssssssssssssssss:
  /sssssssssssssssssssssssssssssssssss/
 :sssssssssssssoosssssssoosssssssssssss:
 osssssssssssssoosssssssoossssssssssssso
 osssssssssssyyyyhhhhhhhyyyyssssssssssso
 /yyyyyyhhdmmmmNNNNNNNNNNNmmmmdhhyyyyyy/
  smmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmms
   /dNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNd/
    `:sdNNNNNNNNNNNNNNNNNNNNNNNNNds:`
       `-+shdNNNNNNNNNNNNNNNdhs+-`
             `.-:///////:-.`

EOM

source updxvk.cfg

ROOT=$PWD

# Use custom compiler paths if defined
if [ -n "${CUSTOM_MINGW_PATH}" ]; then
  PATH=${CUSTOM_MINGW_PATH}/bin:${CUSTOM_MINGW_PATH}/lib:${CUSTOM_MINGW_PATH}/include:${PATH}
fi
if [ -n "${CUSTOM_GCC_PATH}" ]; then
  PATH=${CUSTOM_GCC_PATH}/bin:${CUSTOM_GCC_PATH}/lib:${CUSTOM_GCC_PATH}/include:${PATH}
fi

_exit_cleanup() {
  rm -rf "$ROOT/DXVKBUILD/dxvk-$DXVK_BRANCH"
  echo -e "\nexit cleanup done"
}

build() {
mkdir -p DXVKBUILD
mkdir -p DXVKBUILD/patches

if [ "$DIRTYIN" != "2" ]; then
  if [ -e "dxvk-$DXVK_BRANCH.dxvkdirty" ] || [ "$DIRTYIN" == "1" ]; then
  rm -R -f dxvk-"$DXVK_BRANCH"
  echo "#################"
  echo ""
  echo "YOUR TREE WAS CONSIDERED DIRTY AND HAS BEEN CLEARED"
  echo ""
  echo "#################"
  rm "$DXVK_BRANCH".dxvkdirty
  fi
else
  echo "#################"
  echo ""
  echo "YOU DIRTY BOI.."
  echo ""
  echo "#################"
fi

mkdir dxvk-"$DXVK_BRANCH"

cd dxvk-"$DXVK_BRANCH"

if [ ! -e package-release.sh ]; then
  git init .
  git remote add -t \* -f origin https://github.com/doitsujin/dxvk.git
  git checkout "$DXVK_BRANCH"
fi

if [ "$DXVK_AUTOUPDATE" == "1" ]; then
  git pull
fi

if [ -n "$DXVK_COMMIT" ] && [ "$CUSTOM_COMMIT" == "1" ]; then
  git checkout "$DXVK_COMMIT"
fi

GIT_HEAD=$(git rev-parse HEAD)-`date '+%Y-%m-%d-%H:%M:%S'`

if [ "$_async" == "true" ]; then
  mv ../DXVKBUILD/patches/dxvk-async.dxvkpatchb ../DXVKBUILD/patches/dxvk-async.dxvkpatch 2>/dev/null
else
  mv ../DXVKBUILD/patches/dxvk-async.dxvkpatch ../DXVKBUILD/patches/dxvk-async.dxvkpatchb 2>/dev/null
fi

if [ "$_nativeopt" == "true" ]; then
  mv ../DXVKBUILD/patches/nativeopt.dxvkpatchb ../DXVKBUILD/patches/nativeopt.dxvkpatch 2>/dev/null
else
  mv ../DXVKBUILD/patches/nativeopt.dxvkpatch ../DXVKBUILD/patches/nativeopt.dxvkpatchb 2>/dev/null
fi

# Community patches
if [ -n "$_community_patches" ]; then
  _community_patches=($_community_patches)
  for _p in ${_community_patches[@]}; do
   ln -s $ROOT/../community-patches/dxvk/$_p $ROOT/DXVKBUILD/patches/
  done
fi

if [ "$PATCHIN" == "1" ]; then
  for F in ../DXVKBUILD/patches/*.dxvkrevert; do
    if [ -e "${F}" ]; then
      echo "#################"
      echo ""
      echo "REVERTING PATCH ${F}"
      echo ""
      echo "#################"
      patch -Np1 -R < ${F} && echo "This means that branch $DXVK_BRANCH was altered by patching and will be cleared next time you build" >> ../"$DXVK_BRANCH".dxvkdirty || exit 1
    else
      echo "#################"
      echo ""
      echo "NO REVERT PATCH DETECTED - MOVING ON"
      echo ""
      echo "#################"
    fi
  done
  for F in ../DXVKBUILD/patches/*.dxvkpatch; do
    if [ -e "${F}" ]; then
      echo "#################"
      echo ""
      echo "APPLYING PATCH ${F}"
      echo ""
      echo "#################"
      patch -Np1 < ${F} && echo "This means that branch $DXVK_BRANCH was altered by patching and will be cleared next time you build" >> ../"$DXVK_BRANCH".dxvkdirty || exit 1
    else
      echo "#################"
      echo ""
      echo "NO PATCH DETECTED - MOVING ON"
      echo ""
      echo "#################"
    fi
  done
fi

# Community patches cleanup
if [ -n $_community_patches ]; then
  for _p in ${_community_patches[@]}; do
   rm -f $ROOT/DXVKBUILD/patches/${_p}
  done
fi

if pacman -Qq ccache &> /dev/null; then
  echo 'ccache was found and will be used'
  sed -i "s|c = 'i686-w64-mingw32-gcc'|c = ['ccache', 'i686-w64-mingw32-gcc']|g" build-win32.txt
  sed -i "s|c = 'x86_64-w64-mingw32-gcc'|c = ['ccache', 'x86_64-w64-mingw32-gcc']|g" build-win64.txt
  sed -i "s|cpp = 'i686-w64-mingw32-g++'|cpp = ['ccache', 'i686-w64-mingw32-g++']|g" build-win32.txt
  sed -i "s|cpp = 'x86_64-w64-mingw32-g++'|cpp = ['ccache', 'x86_64-w64-mingw32-g++']|g" build-win64.txt
else
  echo ""
  echo 'ccache was not found and will not be used'
fi

echo "#################"
echo ""
echo "BUILDING"
echo ""
echo "#################"
./package-release.sh "$DXVK_BRANCH" ../DXVKBUILD --no-package

if [ -d ../DXVKBUILD/dxvk-"$DXVK_BRANCH"/x32 ] && [ -d ../DXVKBUILD/dxvk-"$DXVK_BRANCH"/x64 ]; then
  mkdir -p ../DXVKBUILD/"$DXVK_BRANCH"/"$GIT_HEAD"
  mv -v -T ../DXVKBUILD/dxvk-"$DXVK_BRANCH"/x32 ../DXVKBUILD/"$DXVK_BRANCH"/"$GIT_HEAD"/x32
  cp ../DXVKBUILD/setup_dxvk32.sh ../DXVKBUILD/"$DXVK_BRANCH"/"$GIT_HEAD"/x32/setup_symlink_dxvk.sh
  mv -v -T ../DXVKBUILD/dxvk-"$DXVK_BRANCH"/x64 ../DXVKBUILD/"$DXVK_BRANCH"/"$GIT_HEAD"/x64
  cp ../DXVKBUILD/setup_dxvk64.sh ../DXVKBUILD/"$DXVK_BRANCH"/"$GIT_HEAD"/x64/setup_symlink_dxvk.sh
  cp ../DXVKBUILD/dxvk-"$DXVK_BRANCH"/setup_dxvk.sh ../DXVKBUILD/"$DXVK_BRANCH"/"$GIT_HEAD"/setup_dxvk.sh
  rm -R -f ../DXVKBUILD/dxvk-"$DXVK_BRANCH"
  echo "Your files were built in $ROOT/DXVKBUILD/$DXVK_BRANCH/$GIT_HEAD"
  rm -f ../DXVKBUILD/"$DXVK_BRANCH"/last-HEAD
  echo "CURRENT_HEAD=$GIT_HEAD" >> ../DXVKBUILD/"$DXVK_BRANCH"/last-HEAD
  rm -f ../DXVKBUILD/"$DXVK_BRANCH"/latest
  ln -s "$GIT_HEAD" "$ROOT"/DXVKBUILD/"$DXVK_BRANCH"/latest
else
  rm -rf ../DXVKBUILD/*-"$DXVK_BRANCH"
fi

}

update() {

if [ -d "$ROOT/DXVKBUILD" ]; then

  source "$ROOT/DXVKBUILD/$DXVK_BRANCH/last-HEAD"

  # kill wineserver before installation to make sure correct wine version is used
  wineserver -k

  WINECMD=${WINE-wine}

  if [ $WINECMD = "wine" ]; then
    if [ $WINEARCH = "win64" ]; then
        WINECMD="wine64"
    else
        WINECMD="wine"
    fi
  fi

  if [ -z "$2" ]; then
    cd "$ROOT/DXVKBUILD/$DXVK_BRANCH/$CURRENT_HEAD"
  elif [ -d "$ROOT/DXVKBUILD/$2" ]; then
    cd "$ROOT/DXVKBUILD/$2"
  else
    echo "#################################"
    echo ""
    echo "  DXVKBUILD/$2 directory not found !!"
    echo ""
    echo "#################################"
  fi

  if [ -d "x32" ] && [ -d "x64" ]; then
    WINEARCH="$WINEARCH" WINEPREFIX="$WINEPREFIX" bash "$_DXVKALIAS"/setup_symlink_dxvk.sh

    if [ $WINEARCH = "win64" ]; then
        WINEARCH="$WINEARCH" WINEPREFIX="$WINEPREFIX" bash x32/setup_symlink_dxvk.sh
    fi

    echo "#########################################"
    echo ""
    echo "  DXVK updated in $WINEPREFIX - $WINEARCH"
    echo ""
    echo "#########################################"
  fi

  wineserver -k

else
  echo "################################################################"
  echo ""
  echo "You need to build before you can update ! Run updxvk build first"
  echo ""
  echo "################################################################"
fi
}

# External / Dynamic
if [ -n "$1" ] && [ "$1" != "batch" ] && [ "$1" != "build" ] && [ "$1" != "lutris" ] && [ "$1" != "proton-tkg" ]; then
  if [ -d "$1" ]; then
    WINEPREFIX="$1"
    if [ "$2" == "32" ]; then
      echo "x86 prefix"
      WINEARCH="win32"
      _DXVKALIAS="x32"
    elif [ "$2" == "64" ]; then
      echo "x64 prefix"
      WINEARCH="win64"
      _DXVKALIAS="x64"
    elif [ -d "$1/drive_c/Program Files (x86)" ]; then
      echo "assuming x64 prefix"
      WINEARCH="win64"
      _DXVKALIAS="x64"
    else
      echo "assuming x86 prefix"
      WINEARCH="win32"
      _DXVKALIAS="x32"
    fi
    if [ "$2" == "vulkansdk" ]; then
      WINEARCH="$WINEARCH" WINEPREFIX="$WINEPREFIX" "$WINECMD" regedit /S "$ROOT/DXVKBUILD/vulkansdk/vulkan.reg"

      if [ ! -f "$ROOT/DXVKBUILD/vulkansdk/VulkanSDK-1.1.77.0-Installer.exe" ]; then
        wget https://sdk.lunarg.com/sdk/download/1.1.77.0/windows/VulkanSDK-1.1.77.0-Installer.exe?Human=true -O "$ROOT/DXVKBUILD/vulkansdk/VulkanSDK-1.1.77.0-Installer.exe"
      fi

      WINEARCH="$WINEARCH" WINEPREFIX="$WINEPREFIX" "$WINECMD" "$ROOT/DXVKBUILD/vulkansdk/VulkanSDK-1.1.77.0-Installer.exe /S"
      cp "$ROOT/DXVKBUILD/vulkansdk/winevulkan.json" "$WINEPREFIX/drive_c/windows/winevulkan.json"
      echo "Vulkan SDK installation completed."
    fi
  fi
  update
fi

# Batch
if [ "$1" == "batch" ] && [ ! -z "$PREFIXES_ROOT" ]; then
  for D in $PREFIXES_ROOT/*; do
    if [ -d "${D}" ]; then
      echo "${D}"
      if [ -d "${D}/drive_c" ]; then
        WINEPREFIX="${D}"
        if [ -d "${D}/drive_c/Program Files (x86)" ]; then
          WINEARCH="win64"
          _DXVKALIAS="x64"
        else
          WINEARCH="win32"
          _DXVKALIAS="x32"
        fi
        update
      fi
    fi
  done
fi

# Lutris
if [ "$1" == "lutris" ]; then

  wineserver -k

    if [ ! -f ./DXVKBUILD/"$DXVK_BRANCH/"last-HEAD ]; then

      echo "You need to build before you can update ! Run updxvk build first"

    else

      source "$ROOT/DXVKBUILD/$DXVK_BRANCH/last-HEAD"

      rm -rv "$HOME"/.local/share/lutris/runtime/dxvk/TkG/x64/*
      rm -rv "$HOME"/.local/share/lutris/runtime/dxvk/TkG/x32/*
      mkdir -p "$HOME"/.local/share/lutris/runtime/dxvk/TkG/x64
      mkdir -p "$HOME"/.local/share/lutris/runtime/dxvk/TkG/x32
      cp -rv ./DXVKBUILD/"$DXVK_BRANCH"/"$CURRENT_HEAD"/x64/* "$HOME"/.local/share/lutris/runtime/dxvk/TkG/x64
      cp -rv ./DXVKBUILD/"$DXVK_BRANCH"/"$CURRENT_HEAD"/x32/* "$HOME"/.local/share/lutris/runtime/dxvk/TkG/x32

      echo ""
      echo "###########################################################"
      echo ""
      echo "Put 'TkG' as DXVK version in lutris to use your fresh build"
      echo ""
      echo "###########################################################"

    fi

fi

# Proton-tkg
if [ "$1" == "proton-tkg" ]; then

  wineserver -k

    if [ ! -f ./DXVKBUILD/"$DXVK_BRANCH"/last-HEAD ]; then

      echo "You need to build before you can update ! Run updxvk build first"

    else

      source "$ROOT/DXVKBUILD/$DXVK_BRANCH/last-HEAD"

      rm -rf ../proton-tkg/dxvk
      mkdir -p ../proton-tkg/dxvk/x64
      mkdir -p ../proton-tkg/dxvk/x32
      cp -rv ./DXVKBUILD/"$DXVK_BRANCH"/"$CURRENT_HEAD"/x64/* ../proton-tkg/dxvk/x64
      cp -rv ./DXVKBUILD/"$DXVK_BRANCH"/"$CURRENT_HEAD"/x32/* ../proton-tkg/dxvk/x32

      echo ""
      echo "###############################################################"
      echo ""
      echo "This DXVK build will be integrated to your next Proton-tkg build"
      echo ""
      echo "###############################################################"

    fi

fi

# Build from latest master branch
if [ "$1" == "build" ]; then

  time build

fi

trap _exit_cleanup EXIT SIGTERM
